### ISSUE TITLE
Input Field Responsiveness Issue in Mobile Screen

### ISSUE THREAD

**Issue by KHemanth2001** [Pa1mekala37/MERN-URL-Shortener#6]
![WhatsApp Image 2024-02-28 at 11 33 19_62c80eca](https://github.com/Pa1mekala37/MERN-URL-Shortener/assets/130360139/a84ae482-c9d1-499d-9a1f-abdb0fd2b9e8)

**Comment by Pa1mekala37** [comment]
issue resolved now
